# Generated by Django 5.2.8 on 2025-12-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_item_student_registration_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='college',
        ),
        migrations.AddField(
            model_name='item',
            name='numbers',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='max_participants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
