# Generated by Django 5.2.8 on 2025-12-02 03:55

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_item_college_item_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_card_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.student_upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.college')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item')),
                ('students', models.ManyToManyField(to='accounts.student')),
            ],
        ),
    ]
