# Generated by Django 5.2.8 on 2025-12-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_id_card_file_alter_student_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
