# Generated by Django 5.2.8 on 2025-12-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_college_raw_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='raw_password',
        ),
    ]
