# Generated by Django 5.2.8 on 2025-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_college_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Group', 'Group')], default='Single', max_length=10),
        ),
    ]
