# Generated by Django 5.2.8 on 2025-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('single', 'single'), ('group', 'group')], max_length=10),
        ),
    ]
