# Generated by Django 5.2.8 on 2025-12-21 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_brochure_sitesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='password',
        ),
        migrations.RemoveField(
            model_name='college',
            name='username',
        ),
        migrations.AddField(
            model_name='college',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to=settings.AUTH_USER_MODEL),
        ),
    ]
