# Generated by Django 5.2.8 on 2025-12-24 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_college_password_remove_college_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('position', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd')], null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('message', models.TextField(blank=True)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='appeal_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.college')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_appeals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
