# Generated by Django 5.2.8 on 2025-12-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_appealnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochure',
            name='image',
        ),
        migrations.AddField(
            model_name='brochure',
            name='document_type',
            field=models.CharField(choices=[('brochure', 'Brochure'), ('schedule', 'Schedule'), ('blueprint', 'Blueprint')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brochure',
            name='file',
            field=models.FileField(default=1, upload_to='public_docs/'),
            preserve_default=False,
        ),
    ]
