# Generated by Django 5.2.8 on 2025-12-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_brochure_image_brochure_document_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brochure',
            new_name='PublicDocument',
        ),
    ]
