# Generated by Django 5.2.8 on 2025-12-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_brochure_publicdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='document_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='file',
            field=models.FileField(upload_to='public_documents/'),
        ),
    ]
