# Generated by Django 5.2.8 on 2025-12-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_uploaded_at_publicdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicdocument',
            name='document_type',
            field=models.CharField(choices=[('brochure', 'Brochure'), ('schedule', 'Schedule'), ('blueprint', 'Blueprint')], max_length=20),
        ),
    ]
